[tool.poetry]
name = "arena-controls"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "arena_controls"}]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^3.0.0"
flask-apscheduler = "^1.13.1"
flask-socketio = "^5.3.6"
httpx = "^0.25.1"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
